# Generated by Django 2.0 on 2018-01-12 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('spot', models.CharField(choices=[('TP', 'Tapiri'), ('SF', 'Salão de Festas')], max_length=2, verbose_name='ambiente')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('canceled', models.BooleanField(default=False, verbose_name='cancelado')),
                ('expired', models.BooleanField(default=False, verbose_name='expirado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ('-date',),
            },
        ),
    ]
