# Generated by Django 2.0 on 2018-01-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20180112_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
