# Generated by Django 2.0 on 2018-01-20 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_termsofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsofuse',
            name='file',
            field=models.FileField(upload_to='reservations/termsofuse/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'O sistema só permite o upload de arquivos PDF.')]),
        ),
    ]
