# Generated by Django 2.0 on 2017-12-30 03:49

import apvma.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('CL', 'Coronel'), ('TCL', 'Tenente-Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente')], max_length=4, verbose_name='posto')),
                ('full_name', models.CharField(max_length=100, verbose_name='nome completo')),
                ('war_name', models.CharField(max_length=20, verbose_name='nome de guerra')),
                ('cpf', models.CharField(max_length=11, validators=[apvma.accounts.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='email intraer')),
                ('apartment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'morador',
                'verbose_name_plural': 'moradores',
            },
        ),
    ]
