# Generated by Django 2.0 on 2018-01-05 18:06

import apvma.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('RN', 'Rio Negro'), ('RS', 'Rio Solimões'), ('RA', 'Rio Amazonas'), ('RJ', 'Rio Japurá')], max_length=2, verbose_name='bloco')),
                ('number', models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('601', '601'), ('602', '602'), ('603', '603'), ('604', '604')], max_length=3, verbose_name='número')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apartamento',
                'verbose_name_plural': 'apartamentos',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('CL', 'Coronel'), ('TCL', 'Tenente-Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', '1º Tenente'), ('2T', '2º Tenente')], max_length=4, verbose_name='posto')),
                ('full_name', models.CharField(max_length=100, verbose_name='nome completo')),
                ('war_name', models.CharField(max_length=20, verbose_name='nome de guerra')),
                ('cpf', models.CharField(max_length=11, validators=[apvma.accounts.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='email intraer')),
                ('apartment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Apartment')),
            ],
            options={
                'verbose_name': 'morador',
                'verbose_name_plural': 'moradores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('block', 'number')},
        ),
    ]
