# Generated by Django 2.0 on 2018-01-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email ZIMBRA'),
        ),
    ]
