# Generated by Django 2.0 on 2018-02-03 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_internalregiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalregiment',
            name='file',
            field=models.FileField(upload_to='core/documents/internal_regiment/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'O sistema só permite o upload de arquivos PDF.')]),
        ),
    ]
