# Generated by Django 2.0 on 2018-02-04 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180203_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='core/documents/statute/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'O sistema só permite o upload de arquivos PDF.')])),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Estatuto',
                'verbose_name_plural': 'Estatuto',
            },
        ),
    ]
