# Generated by Django 2.0 on 2018-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='mês de referência')),
                ('file', models.FileField(upload_to='accountability/%Y')),
            ],
            options={
                'verbose_name': 'prestação de conta',
                'verbose_name_plural': 'prestação de contas',
            },
        ),
    ]
