# Generated by Django 2.0 on 2018-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountability',
            options={'ordering': ('-date',), 'verbose_name': 'prestação de conta', 'verbose_name_plural': 'prestações de contas'},
        ),
        migrations.AlterField(
            model_name='accountability',
            name='file',
            field=models.FileField(upload_to='accountability/'),
        ),
    ]
