# Generated by Django 2.0 on 2018-02-04 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assembly/minutes/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'O sistema só permite o upload de arquivos PDF.')], verbose_name='ata da assembleia')),
                ('date', models.DateField(verbose_name='data da assembleia')),
            ],
            options={
                'verbose_name': 'Ata de Assembleia',
                'verbose_name_plural': 'Atas de Assembleia',
            },
        ),
    ]
