# Generated by Django 2.0 on 2018-02-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='estimada de chegada')),
                ('description', models.TextField(max_length=50, verbose_name='descrição')),
                ('arrival', models.DateTimeField(blank=True, null=True, verbose_name='chegada')),
                ('exit', models.DateTimeField(blank=True, null=True, verbose_name='saída')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='apartamento')),
            ],
            options={
                'verbose_name': 'visita autorizada',
                'verbose_name_plural': 'visitas autorizadas',
                'ordering': ('datetime', 'user', 'description'),
            },
        ),
    ]
