# Generated by Django 2.0 on 2018-02-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statute'),
        ('visitors', '0002_auto_20180223_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-datetime', 'apartment', 'description'), 'verbose_name': 'Visita Autorizada', 'verbose_name_plural': 'Visitas Autorizadas'},
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
        migrations.AddField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Apartment', verbose_name='apartamento'),
            preserve_default=False,
        ),
    ]
